version: '2'

# based off compose-sample-2, only we build nginx.conf into image
# uses sample HTML static site from https://startbootstrap.com/themes/agency/

services:
  proxy:
    build:
      context: .                      # pwd the current directory
      dockerfile: nginx.Dockerfile    # the Dockerfile name put it here. to build from it
      image: nginx-custom             # the name of image will create.
    ports:
      - '80:80'
  web:
    image: httpd
    volumes:
      - ./html:/usr/local/apache2/htdocs/
